app/models.py
from app import db
from datetime import datetime
import re

def slugify(s):
	pattern = r'[^\w+]'
	return re.sub(pattern, '-', s)


class Post(db.Model):
	id = db.Column(db.Integer, primary_key=True)
	title = db.Column(db.String(140))
	slug = db.Column(db.Text)
	created = db.Column(db.DateTime, default=datetime.now())

	def __init__(self, *args, **kwargs):
		super(Post, self).__init__(*args, **kwargs)
		self.generate_slug()


	def generate_slug(self):
		if self.title:
			self.slug = slugify(self.title)

	def __repr__(self):
		return '<Post id: {}, title: {}>'.format(self.id, self.title)

app/app.py
from flask import Flask
from config import Configuration
from flask_sqlalchemy import SQLAlchemy 

from posts.blueprint import posts


app = Flask(__name__)
app.config.from_object(Configuration)

db = SQLAlchemy(app)


app.register_blueprint(posts, url_prefix='/blog')






app/main.py
from app import app
from app import db
import view

if __name__ == '__main__':
	app.run(debug=True)





app/posts/blueprint.py
from flask import Blueprint
from flask import render_template

posts = Blueprint('posts', __name__, template_folder='templates')

@posts.route('/')
def index():
	return render_template('/posts/index.html')

app/templates/base.html
<!DOCTYPE html>
<html lang='en'>
<head>
	<meta charset='UTF-8'>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
        crossorigin="anonymous">
  <title>
    {% block title %}
    {% endblock %} | Flask app
  </title>
</head>
<body _c_t_common="1">
    
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('index') }}">Flask</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{ url_for('posts.index') }}">Blog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

<main class="container">
  <div class="bg-light p-5 rounded">
    <h1>Navbar example</h1>
    <p class="lead">This example is a quick exercise to illustrate how the top-aligned navbar works. As you scroll, this navbar remains in its original position and moves with the rest of the page.</p>
    
  </div>
</main>

<div class='container'>
	<div class="row">
		<h1>
      {% block content_title %}

      {% endblock %}  
    </h1>
    {% block content %}

    {% endblock %}
	</div>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
        crossorigin="anonymous"></script>

      

</body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block title %}
	Index page
{% endblock %}

{% block content_title %}
	Index page
{% endblock %}

{% block content %}
	Some content
{% endblock %}